# Puppet Forge
mod 'puppetlabs/apt'
mod 'puppetlabs/ntp'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/inifile'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/firewall'
mod 'razorsedge/openvmtools'
mod 'puppetlabs/vcsrepo'
mod 'saz/sudo'
mod 'saz/motd'
mod 'thias/bind'

